Event Portal/project/events/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField,IntegerField
from wtforms.validators import DataRequired,Length,ValidationError
from wtforms.fields.html5 import DateField
from datetime import date, timedelta

class EventForm(FlaskForm):
    title = StringField('Title',validators=[DataRequired(),Length(min=5)])
    description = TextAreaField('Description',validators=[DataRequired(),Length(min=30)])
    event_date = DateField('Event Date', validators=[DataRequired()])
    state = SelectField('State',validate_choice=False, validators=[DataRequired()])
    city = SelectField('city', validate_choice=False, validators=[DataRequired()])
    place = StringField('Place', validators=[DataRequired()])
    category = SelectField('Category', choices=['Seminar', 'Conference', 'Trade shows', 'Workshops','IT'])
    seat = IntegerField('Seat available', validators=[DataRequired()])

    submit = SubmitField('Post')

    def validate_event_date(self,field):
        check_date = date.today()+timedelta(days=2)
        if check_date > field.data:
            raise ValidationError('Please select a date atleast 2 days later')

    #check city name

Event Portal/project/events/views.py
from flask import (Blueprint,render_template,redirect,url_for,flash,
        request,current_app,jsonify,session,abort)
from flask_login import current_user,login_required
from project.events.forms import EventForm
from project.models import Event,User
from project import db
import os, json
from flask_weasyprint import HTML, render_pdf

def pprint(message):
    print(f'\n#################\n{message}\n')


events = Blueprint('events',__name__)

@events.route('/event/new',methods=['POST','GET'])
@login_required
def new_event():
    form = EventForm()
    with open(os.path.join(current_app.root_path,'states-and-districts.json')) as f:
        data = json.load(f)
        states = [ data['states'][i]['state'] for i in range(len(data['states']))]
        city = data['states'][0]['districts']
        pprint(states)
    form.state.choices = states
    form.city.choices = city
    
    if form.validate_on_submit():
        event = Event(
                author = current_user,
                title = form.title.data,
                description = form.description.data,
                event_date = form.event_date.data,
                state = form.state.data,
                city = form.city.data,
                category = form.category.data,
                seat = form.seat.data,
                place = form.place.data,
                )
        db.session.add(event)
        db.session.commit()
        flash('Your Event has been created','success')
        return redirect(url_for('main.home'))
    return render_template('create_event.html', title='New Event', form=form, legend='Create Event')

@events.route('/city/<state>')
def city(state):
    pprint('called')
    with open(os.path.join(current_app.root_path,'states-and-districts.json')) as f:
        data = json.load(f)
        for data in data['states']:
            if data['state'] == state:
                districts = data['districts']
                break

    cityArray = []

    for city in districts:
        cityObj = {}
        cityObj['name'] = city
        cityArray.append(cityObj)

    return jsonify({'cities' : cityArray})

@events.route('/event/<int:event_id>')
def event(event_id):
    event = Event.query.get_or_404(event_id)
    if current_user in event.participents:
        pprint('found')

    return render_template('event.html',title=event.title,event=event)

@events.route('/event/<int:event_id>/update',methods=['POST','GET'])
@login_required
def update_event(event_id):
    form = EventForm()
    event = Event.query.get(event_id)
    if event.author != current_user:
        abort(403)
    if form.validate_on_submit():
        event.title = form.title.data
        event.description = form.description.data
        event.event_date = form.event_date.data
        event.category = form.category.data
        event.seat = form.seat.data
        event.place = form.place.data

        db.session.commit()
        flash('Event Successfully Updated','success')
        return redirect(url_for('events.event',event_id=event_id))
    elif request.method == 'GET':
        form.title.data = event.title
        form.description.data = event.description
        form.event_date.data = event.event_date
        form.state.choices = [event.state,]
        form.city.choices = [event.city,]
        form.category.data = event.category
        form.seat.data = event.seat
        form.place.data = event.place

    return render_template('create_event.html',legend='Update Event',form=form)

#only need event,becuz we only going to accept request if it submitted through the form 
@events.route('/event/<int:event_id>/delete',methods=['POST'])
@login_required
def delete_event(event_id):
    event = Event.query.get(event_id)
    if event.author != current_user:
        abort(403)
    db.session.delete(event)
    db.session.commit()
    flash('Event Delete successfully','success')
    return redirect(url_for('main.home'))


@events.route('/event/<string:username>')
def user_events(username):
    page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    event = Event.query.filter_by(author=user)\
            .order_by(Event.date_posted.desc()).paginate(per_page=5,page=page)
    return render_template('user_events.html',user=user,events=event)

@events.route('/participate_event/<int:event_id>', methods=['POST','GET'])
@login_required
def participate_in_event(event_id):
    event = Event.query.get(event_id)
    event.participents.append(current_user)
    event.seat = event.seat-1
    db.session.commit()
    return redirect(url_for('events.event', event_id=event_id))

@events.route('/cancel_participate/<int:event_id>', methods=['POST','GET'])
def cancel_participate(event_id):
    event = Event.query.get(event_id)
    event.participents.remove(current_user)
    event.seat = event.seat+1
    db.session.commit()
    return redirect(url_for('events.event', event_id=event_id))


@events.route('/participent_pdf/<event_id>', methods=['GET'])
def participent_pdf(event_id):
    event = Event.query.get(event_id)
    if current_user != event.author:
        abort(403)
    all_participent=[
            [user.username,user.email]
            for user in event.participents]
    html = render_template('view_participent.html', participent=all_participent)
    return render_pdf(HTML(string=html), download_filename= f'{event.title}.pdf')


@events.route('/events')
@login_required
def participated_event():
    return render_template('par.html')


    

Event Portal/project/main/views.py
from flask import render_template, request, Blueprint
from project.models import Event

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page',1,type=int)
    event = Event.query.order_by(Event.date_posted.desc()).paginate(per_page=5,page=page)
    return render_template('home.html',events=event)


@main.route('/about')
def about():
    return render_template('about.html')

Event Portal/project/users/views.py
from flask import (render_template, redirect,flash,
        url_for,Blueprint, request,current_app, abort,session)
from project.users.forms import (RegisterForm, LoginForm, UpdateForm,
        RequestResetForm, ResetPasswordForm)
from project.models import User, Event, generate_password_hash
from flask_login import login_user, logout_user, current_user, login_required
from project import db, mail
from project.users.pic_handler import pic_saver
import os
from flask_mail import Message
from flask_dance.contrib.google import make_google_blueprint, google
import secrets
import requests


users = Blueprint('users',__name__)

google_blueprint = make_google_blueprint(client_id=os.environ.get('CLIENT_ID'),
        client_secret=os.environ.get('CLIENT_SECRET'), offline=True,
        scope=['openid', 'email', 'profile'],
        redirect_to='users.google_login')

@users.route('/register', methods=['POST','GET'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegisterForm()

    if form.validate_on_submit():
        user = User(
                username = form.username.data,
                email = form.email.data,
                password = form.password.data
                )
        db.session.add(user)
        db.session.commit()
        flash(f'Account Successfully Created for {form.username.data}','success')
        return redirect(url_for('users.login')) 
    return render_template('register.html',title='Register',form=form)

@users.route('/login',methods=['POST','GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = LoginForm()
    
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        
        if user and user.check_password(form.password.data):
            if not user.email_varified:
                send_email(user,'Varify Account',link='users.verify_email')
                session['username'] = user.username
                return redirect(url_for('users.verify'))
            login_user(user,remember=form.remember.data)
            next = request.args.get('next')
            if not next or next[0] != '/':
                next = url_for('main.home')
            return redirect(next)
        else:
            flash('Username or Password is incorrect','danger')
    return render_template('login.html',title='Login',form=form)

@users.route('/google')
def google_login():
    next = request.args.get('next')
    print(f'\n {next} \n')
    if current_user.is_authenticated:
        logout(current_user)
    if not google.authorized:
        return redirect(url_for('google.login'))

    resp = google.get("/oauth2/v2/userinfo")
    if resp.ok:
        response = resp.json()
        user = User.query.filter_by(email=response['email']).first()
        if not user:
            r = requests.get(response['picture'])
            filename = f'{response["id"]}.jpg'
            loc = os.path.join(current_app.root_path,'static/profile_pics',filename)
            with open(loc, 'wb') as f:
                f.write(r.content)
            user = User(
                username = response['name'],
                email = response['email'],
                password = secrets.token_hex(12),
                image_file = filename
                )
            db.session.add(user)
            db.session.commit()
        login_user(user)
        return redirect(url_for('main.home'))

    else:
        flash('Something went Wrong','danger')
        return redirect(url_for('users.login'))



@users.route('/verification')
def verify():
    if session.get('username'):
        return render_template('verify.html', username=session['username'])
    else:
        abort(403)

@users.route('/verification/<token>', methods=['POST', 'GET'])
def verify_email(token):
    if current_user.is_authenticated:
        logout(current_user)
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.login'))
    user.email_varified = True
    db.session.commit()
    login_user(user)
    return redirect(url_for('main.home'))



@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route('/account',methods = ['POST','GET'])
@login_required
def account():
    image_file = url_for('static',filename='profile_pics/'+current_user.image_file)
    form = UpdateForm()
    if form.validate_on_submit():
        if form.picture.data:
            old_image = current_app.root_path+image_file
            image_file = pic_saver(form.picture.data,current_user.username)
            current_user.image_file = image_file
            if 'default.jpg' not in old_image: 
                os.remove(old_image)
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account is updated','success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('account.html',title='Account',image_file=image_file,form=form)

def send_email(user,message,link):
    token = user.get_reset_token()
    msg = Message(f'{message}',
            sender='noreply@flasklogin.com',
            recipients=[user.email])
    url = url_for(link, token=token, _external=True)   
    msg.html=render_template('reset.html', message=message, url=url)
    mail.send(msg)

@users.route('/reset_password', methods=['POST', 'GET'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_email(user,'reset password',link='users.reset_token')
        flash('An email as been send with reset password link to your mail', 'info')
        return redirect(url_for('users.login'))

    return render_template('reset_request.html', title='Reset Password',form=form)

@users.route('/reset_password/<token>', methods=['POST', 'GET'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        password = generate_password_hash(form.password.data)
        user.password_hash = password
        user.email_varified = True
        db.session.commit()
        flash('Your Password successfully updated','success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)
        

Event Portal/project/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

Event Portal/project/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
      <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
      	<div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
      </form>
  </div>
{% endblock content %}

Event Portal/project/templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for event in events.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + event.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('events.user_events', username=event.author.username) }}">{{ event.author.username }}</a>
              <small class="text-muted">posted date: {{ event.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h1><a class="article-title" href="{{ url_for('events.event', event_id=event.id) }}">{{ event.title }}</a></h1>
             <small class="text-muted">Event date: {{ event.event_date.strftime('%Y-%m-%d') }}</small>
             <br>
             <small class="text-muted">Event place: {{ event.place }}</small>
             
            <p class="article-content"><h6>{{ event.description[:400] }} ....</h6></p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in events.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if events.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}

Event Portal/project/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Eventer - {{ title }}</title>
    {% else %}
        <title>Eventer</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Eventer</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
            	{% if current_user.is_authenticated %}
            	<a class="nav-item nav-link" href="{{url_for('events.new_event')}}">New event</a>
            	<a class="nav-item nav-link" href="{{url_for('users.account')}}">{{current_user.username}}</a>
            	<a class="nav-item nav-link" href="{{url_for('users.logout')}}">Logout</a>
              	{% else %}
              <a class="nav-item nav-link" href="{{url_for('users.login')}}">Login</a>
              <a class="nav-item nav-link" href="{{url_for('users.register')}}">Register</a>
            	{% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Quick Access</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light"><a href="{{url_for('main.home')}}">Latest Events</a></li>
                {% if current_user.is_authenticated %}
                <li class="list-group-item list-group-item-light"><a href="{{url_for('events.user_events',username=current_user.username)}}">My Events</a></li>
                <li class="list-group-item list-group-item-light"><a href="{{url_for('events.participated_event')}}">Participated Event</a></li>
                {% endif %}
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

Event Portal/project/templates/login.html
{% extends "layout.html" %}
{% block content %}

    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                <a href="{{url_for('users.reset_request')}}">Forgot Password?</a>
            </small>
            </div>
            
        </form>




<a href="{{url_for('users.google_login')}}">
<button type="button" class="google-button">
  <span class="google-button__icon">
    <svg viewBox="0 0 366 372" xmlns="http://www.w3.org/2000/svg"><path d="M125.9 10.2c40.2-13.9 85.3-13.6 125.3 1.1 22.2 8.2 42.5 21 59.9 37.1-5.8 6.3-12.1 12.2-18.1 18.3l-34.2 34.2c-11.3-10.8-25.1-19-40.1-23.6-17.6-5.3-36.6-6.1-54.6-2.2-21 4.5-40.5 15.5-55.6 30.9-12.2 12.3-21.4 27.5-27 43.9-20.3-15.8-40.6-31.5-61-47.3 21.5-43 60.1-76.9 105.4-92.4z" id="Shape" fill="#EA4335"/><path d="M20.6 102.4c20.3 15.8 40.6 31.5 61 47.3-8 23.3-8 49.2 0 72.4-20.3 15.8-40.6 31.6-60.9 47.3C1.9 232.7-3.8 189.6 4.4 149.2c3.3-16.2 8.7-32 16.2-46.8z" id="Shape" fill="#FBBC05"/><path d="M361.7 151.1c5.8 32.7 4.5 66.8-4.7 98.8-8.5 29.3-24.6 56.5-47.1 77.2l-59.1-45.9c19.5-13.1 33.3-34.3 37.2-57.5H186.6c.1-24.2.1-48.4.1-72.6h175z" id="Shape" fill="#4285F4"/><path d="M81.4 222.2c7.8 22.9 22.8 43.2 42.6 57.1 12.4 8.7 26.6 14.9 41.4 17.9 14.6 3 29.7 2.6 44.4.1 14.6-2.6 28.7-7.9 41-16.2l59.1 45.9c-21.3 19.7-48 33.1-76.2 39.6-31.2 7.1-64.2 7.3-95.2-1-24.6-6.5-47.7-18.2-67.6-34.1-20.9-16.6-38.3-38-50.4-62 20.3-15.7 40.6-31.5 60.9-47.3z" fill="#34A853"/></svg>
  </span>
  <span class="google-button__text">Sign in with Google</span>
</button>
</a>

    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

Event Portal/project/templates/par.html
{% extends "layout.html" %}
{% block content %}
    {% for event in current_user.participated_events %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + event.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('events.user_events', username=event.author.username) }}">{{ event.author.username }}</a>
              <small class="text-muted">posted date: {{ event.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h1><a class="article-title" href="{{ url_for('events.event', event_id=event.id) }}">{{ event.title }}</a></h1>
             <small class="text-muted">Event date: {{ event.event_date.strftime('%Y-%m-%d') }}</small>
             <br>
             <small class="text-muted">Event place: {{ event.place }}</small>
             
            <p class="article-content"><h6>{{ event.description[:400] }} ....</h6></p>
          </div>
        </article>
    {% endfor %}
    
{% endblock content %}

Event Portal/project/templates/reset.html
<!DOCTYPE html>
<html>
<head>
<style>
.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  max-width: 300px;
  margin: auto;
  text-align: center;
  font-family: arial;
}

.button{
    border-radius: 2px;
}

.card button {
  border: none;
  outline: 0;
  padding: 12px;
  border-radius: 2px;
  color: white;
  background-color: red;
  text-align: center;
  width: 100%;
  font-size: 18px;
}


</style>
</head>
<body>
<div class="card">
  <h1>Flask Blog</h1>
  <p>To {{message}} please visit the following link,if you did not make this request then simply ignore this mail</p>
  <p><a href="{{url}}"><button>{{message}}</button></a></p>
  <span style="opacity: 0"> {{ randomness }} </span>
</div>

</body>
</html>

Event Portal/project/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

Event Portal/project/templates/user_events.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">events by {{ user.username }} ({{ events.total }})</h1>
    {% for event in events.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + event.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('events.user_events', username=event.author.username) }}">{{ event.author.username }}</a>
              <small class="text-muted">posted date: {{ event.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h1><a class="article-title" href="{{ url_for('events.event', event_id=event.id) }}">{{ event.title }}</a></h1>
             <small class="text-muted">Event date: {{ event.event_date.strftime('%Y-%m-%d') }}</small>
             <br>
             <small class="text-muted">Event place: {{ event.place }}</small>
             
            <p class="article-content"><h6>{{ event.description[:100] }} ...</h6></p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in events.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if events.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('events.user_events', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('events.user_events', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}

Event Portal/project/templates/verify.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
    	<h1>Hey {{username}},</h1><br>
        <p>We're excited to have you get started. First, you need to confirm your account,please check your mail box for confirmation link</p>
        
    </div>
{% endblock content %}