flask_chatapp/project/user/models.py
from project import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model, UserMixin):

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(30), nullable=False, unique=True, index=True)
    username = db.Column(db.String(30), nullable=False, unique=True, index=True)
    password = db.Column(db.String(128), nullable=False)

    def __init__(self, email, username, password):
        self.email = email
        self.username = username
        self.password = generate_password_hash(password)

    def check_user(self, password):
        return check_password_hash(self.password, password)

flask_chatapp/project/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, EmailField, PasswordField, SubmitField, ValidationError
from wtforms.validators import EqualTo, DataRequired
from project.user.models import User

class RegisterForm(FlaskForm):

    email = EmailField('Enter your email address: ', validators=[DataRequired()])
    username = StringField('Enter your username: ', validators=[DataRequired()])
    password = PasswordField('Enter',
                             validators=[DataRequired(), EqualTo('password_confirm', message='passowrd must match')])
    password_confirm = PasswordField('Enter', validators=[DataRequired()])
    submit = SubmitField('Register')

    def check_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already Exist')

    def check_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('username already Exist')

class LoginForm(FlaskForm):

    username = StringField('Enter your username: ', validators=[DataRequired()])
    password = PasswordField('Enter',
                             validators=[DataRequired()])
    submit = SubmitField('Login')

    def check_username(self, field):
        print(1)
        if not User.query.filter_by(username=field.data).first():
            raise ValidationError('username not Exist')

flask_chatapp/project/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from project.config import Config
from flask_socketio import SocketIO

login_manager = LoginManager()

app = Flask(__name__)
app.config.from_object(Config)

socketio = SocketIO(app)

db = SQLAlchemy(app)
Migrate(app, db)

login_manager.init_app(app)
login_manager.login_view = 'user.login'


from project.user.views import user
app.register_blueprint(user, url_prefix='/user')

from project.chat.views import chat
app.register_blueprint(chat, url_prefix='/chat')

flask_chatapp/project/chat/views.py
from flask_socketio import join_room,rooms
from project import socketio as sio
from flask_login import login_required, current_user
from flask import render_template, redirect, session, Blueprint, url_for, request

chat = Blueprint('chat', __name__, template_folder='templates')


@chat.route('/chat')
@login_required
def chat_page():
    room_id = session.get('room_id')
    if not room_id:
        return redirect(url_for('user.welcome'))
    return render_template('chat/chat.html', room=room_id)


@sio.event
def room_join(data):
    join_room(data['room_id'])
    sio.emit('user_join_alert', data)

@sio.event
def send_message(data):
    sio.emit('recive_message', data, to=data['room_id'])

@sio.event
def disconnect():
    sid = request.sid
    room = rooms(sid)
    room.remove(sid)
    room = room[0]
    sio.emit('user_left_alert', current_user.username, room=room)

flask_chatapp/project/user/views.py
from project.user.models import User
from project.user.forms import RegisterForm, LoginForm
from flask import render_template, redirect, session, Blueprint, url_for, request
from project import db,app
from flask_login import login_user, login_required, logout_user, current_user
from functools import wraps


user = Blueprint('user', __name__, template_folder='templates')

def not_login(func):
    """
    if a user is current logged in and try to access to access pages
    like login/register , then redirect the user to welcome page
    :param func:
    :return:
    """
    @wraps(func)
    def inner(*args,**kwargs):
        if current_user.is_authenticated:
            print('running')
            return redirect(url_for('user.welcome'))
        else:
            return func(*args, **kwargs)
    return inner

@user.route('/register', methods=['GET', 'POST'])
@not_login
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        user = User(form.email.data, form.username.data, form.password.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('user.login'))

    return render_template('user/register.html', form=form)

@user.route('/login', methods=['GET', 'POST'])
@not_login
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()

        if user and user.check_user(form.password.data):
            login_user(user)
            next_ =  request.args.get('next')
            if not next_:
                next_ = url_for('user.welcome')

            return redirect(next_)
    return render_template('user/login.html', form=form)


@user.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('user.login'))

@user.route('/welcome')
@login_required
def welcome():
    room_id = request.args.get('room')
    if room_id:
        session['room_id'] = room_id
        return redirect(url_for('chat.chat_page'))
    return render_template('user/welcome_user.html')

flask_chatapp/project/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
  <ul class="nav">

  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('home') }}">Home</a>
  </li>
    {% if current_user.is_authenticated %}
    <li class="nav-link"><a href="{{ url_for('user.welcome') }}">user</a></li>
    <li class="nav-link"><a href="{{ url_for('user.logout') }}">Log Out</a></li>
    {% else %}
    <li class="nav-link"><a href="{{ url_for('user.login') }}">Log In</a></li>
    <li class="nav-link"><a href="{{ url_for('user.register') }}">Register</a></li>
    {% endif %}

</ul>
{% block content %}

{% endblock %}

  </body>
</html>

flask_chatapp/project/templates/home.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  {% if current_user.is_authenticated %}
   <p>Hi {{ current_user.username }}!</p>
  {% else %}
    <p>Please login or register!</p>
  {% endif %}
</div>

{% endblock %}