Zipper/project/files/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField, SelectField
from wtforms.fields.html5 import URLField
from wtforms.validators import DataRequired

class LinkForm(FlaskForm):
    link = URLField('Url', validators=[DataRequired()],
            render_kw={"class":"bg-light form-control border-0 small","placeholder":"Paste url"})
    submit = SubmitField('good')

class AdvancedForm(FlaskForm):
    link = URLField('Url', validators=[DataRequired()],
            render_kw={"class":"form-control", "id":"url", "placeholder":"https://example.com/file.zip"})
    level = SelectField('Select', choices=[('high', 'high'), ('medium', 'Medium'), ('low', 'low')],
            render_kw={"class":"form-select"})
    split = SelectField('Select', choices=[('None', 'N/A'), ('5', '50MB'), ('100', '100MB'), ('250', '250MB'), ('500', '500MB'), ('1000', '1GB')], render_kw={"class":"form-select"})
    format = SelectField('Select', choices=[('7zip', '7Zip'), ('rar', 'Rar'), ('zip', 'Zip')], render_kw={"class":"form-select"})
    submit = SubmitField('good')

Zipper/project/old/files/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField, SelectField
from wtforms.fields.html5 import URLField
from wtforms.validators import DataRequired

class LinkForm(FlaskForm):
    link = URLField('Url', validators=[DataRequired()],
            render_kw={"class":"bg-light form-control border-0 small","placeholder":"Paste url"})
    submit = SubmitField('good')

class AdvancedForm(FlaskForm):
    link = URLField('Url', validators=[DataRequired()],
            render_kw={"class":"form-control", "id":"url", "placeholder":"https://example.com/file.zip"})
    level = SelectField('Select', choices=[('high', 'high'), ('medium', 'Medium'), ('low', 'low')],
            render_kw={"class":"form-select"})
    split = SelectField('Select', choices=[('None', 'N/A'), ('5', '50MB'), ('100', '100MB'), ('250', '250MB'), ('500', '500MB'), ('1000', '1GB')], render_kw={"class":"form-select"})
    format = SelectField('Select', choices=[('7zip', '7Zip'), ('rar', 'Rar'), ('zip', 'Zip')], render_kw={"class":"form-select"})
    submit = SubmitField('good')

Zipper/project/files/views.py
from flask import (Blueprint, url_for, redirect, render_template,
        request, flash, current_app, send_file, abort)
from flask_login import login_required,current_user
from project.files.forms import LinkForm, AdvancedForm
from project.files.utils import file_details,file_type
from project.models import Folder,User,SubFiles
from project import db
import subprocess,os
from threading import Thread


script_location = os.path.join(os.getcwd(),'project/storage')
print(script_location)

files = Blueprint('files', __name__)

def asyn_run_command(filename, command,user_id,split=None):
    folder = Folder.query.filter_by(name=filename).filter_by(user_id=user_id).first()
    result = subprocess.run(command, shell=True, cwd=script_location, stdout=subprocess.PIPE)
    if result.returncode == 0:
        if split:
            size,location,*subfiles,_ = result.stdout.decode().split('\n')
            folder.size = int(int(size)/1024)
            folder.location = location
            folder.splited = True
            for subfile in subfiles:
                name,size = subfile.split(' :')
                size = int(int(size)/1024)
                location = os.path.join(folder.location,name)
                sub = SubFiles(
                        name = name,
                        size = size,
                        location = location,
                        folder_id = folder.id
                        )
                db.session.add(sub)
            folder.progress = 'Finished'
        else:
            size,location,_ = result.stdout.decode().split('\n')
            folder.size = int(int(size)/1024)
            folder.location = location
            folder.progress = 'Finished'
    elif result.returncode == 2:
        folder.progress = 'Virus'
        folder.virus = True
    elif result.returncode == 1:
        folder.progress = 'Failed'
    db.session.commit()

def run_command(filename, url, location, user_id, split=None, level=9):
    command = f"./download.sh -u '{url}' -l '{location}' -f '{filename}' -c {level}"
    if split:
        command += f' -s {split}'
    print(command)
    Thread(target=asyn_run_command, args=(filename,command,user_id,split)).start()


@files.route('/files', methods=['POST','GET'])
@login_required
def file():
    link_form = LinkForm()
    
    if link_form.validate_on_submit():
        details = file_details(link_form.link.data)
        print(details)

        if not details:
            flash('Cant find downloading link','danger')
            return redirect(url_for('files.file'))

        filename,url,size,content_type = details
        size = int(int(size)/1024)
        if size/1024 > 200:
            flash('Maximum file size is 200','danger')
            return redirect(url_for('files.file'))
        content_type = file_type(content_type)

        folder = Folder.query.filter_by(name=filename).filter_by(user_id=current_user.id).first()
        if folder:
            flash(f'{filename} already exist','danger')
            link_form.link.data=''
            return redirect(url_for('files.file'))
        
        file_location = os.path.join(script_location,current_user.username+f'/{filename}')

        folder = Folder(
                name = filename,
                location = current_user.username,
                size = size,
                content_type = content_type,
                user_id = current_user.id,
                file_location = file_location
                )
        db.session.add(folder)
        db.session.commit()
        run_command(filename=filename,url=url,location=folder.location,user_id=current_user.id)
        link_form.link.data = ''
        flash(f'{details[0]} is successfully added to the list','success')
        return redirect('/files')
    return render_template('files.html', link_form=link_form, files=current_user.files)

@files.route('/show')
def showfolder():
    data = [ str(file) for file in current_user.files]
    print(data)
    return 'fskjfl'

@files.route('/share/<string:token>')
def share_link(token):
    folder = Folder.check_token(token)
    if folder is None:
        abort(404)
    location = os.path.join(script_location, folder.location)
    filename = location.split('/')[-1]
    return send_file(location, as_attachment=True)

@files.route('/get_link/<int:id>')
@login_required
def share(id):
    link_form = LinkForm()
    folder = Folder.query.get(id)
    if not folder:
        return redirect('/files')
    if folder.owner != current_user or folder.progress != 'Finished':
        abort(403)
    token = folder.get_token()
    link = url_for('files.share_link',token=token,_external=True)
    return render_template('link_copy.html',link=link, link_form=link_form)


@files.route('/download/<int:id>')
@login_required
def download(id):
    folder = Folder.query.get(id)
    if not folder:
        return redirect('/files')
    if folder.owner != current_user or folder.progress != 'Finished':
        abort(403)
    location = os.path.join(script_location, folder.location)
    filename = location.split('/')[-1]
    return send_file(location, as_attachment=True)

@files.route('/subfiles/share/<string:token>')
def sub_share_link(token):
    folder = SubFiles.check_token(token)
    if folder is None:
        abort(404)
    location = os.path.join(script_location, folder.location)
    filename = location.split('/')[-1]
    return send_file(location, as_attachment=True)

@files.route('/subfiles/get_link/<int:id>')
@login_required
def sub_share(id):
    link_form = LinkForm()
    folder = SubFiles.query.get(id)
    if not folder:
        return redirect('/files')
    if folder.main.owner != current_user or folder.main.progress != 'Finished':
        abort(403)
    token = folder.get_token()
    link = url_for('files.sub_share_link',token=token,_external=True)
    return render_template('link_copy.html',link=link, link_form=link_form)


@files.route('/subfiles/download/<int:id>')
@login_required
def sub_download(id):
    folder = SubFiles.query.get(id)
    if not folder:
        return redirect('/files')
    if folder.main.owner != current_user or folder.main.progress != 'Finished':
        abort(403)
    location = os.path.join(script_location, folder.location)
    filename = location.split('/')[-1]
    return send_file(location, as_attachment=True)

@files.route('/advanced', methods=["POST", "GET"])
@login_required
def advanced():
    link_form = LinkForm()
    advanced_form = AdvancedForm()
    if advanced_form.validate_on_submit():
        details = file_details(advanced_form.link.data)

        if not details:
            flash('Cant find downloading link','danger')
            return redirect(url_for('files.file'))

        filename,url,size,content_type = details
        size = int(int(size)/1024)
        if size/1024 > 200:
            flash('Maximum file size is 200','danger')
            return redirect(url_for('files.file'))
        content_type = file_type(content_type)

        folder = Folder.query.filter_by(name=filename).filter_by(user_id=current_user.id).first()
        if folder:
            flash(f'{filename} already exist','danger')
            link_form.link.data=''
            return redirect(url_for('files.file'))

        file_location = os.path.join(script_location,current_user.username+f'/{filename}')

        folder = Folder(
                name = filename,
                location = current_user.username,
                size = size,
                content_type = content_type,
                user_id = current_user.id,
                file_location =file_location
                )
        db.session.add(folder)
        db.session.commit()
        level = advanced_form.level.data
        split = advanced_form.split.data 
        if level == 'medium':
            level = 5
        elif level == 'low':
            level = 2
        else:
            level = 9
        split = None if split == "None" else split
        run_command(filename=filename,url=url,location=folder.location, user_id=current_user.id, level=level, split=split)
        link_form.link.data = ''
        advanced_form.link.data = ''
        flash(f'{details[0]} is successfully added to the list','success')
        return redirect('/files')
    return render_template('advanced.html', link_form=link_form, advanced_form=advanced_form)

@files.route('/files/subfiles/<int:folder_id>')
@login_required
def subfiles(folder_id):
    link_form = LinkForm()
    folder = Folder.query.get(folder_id)
    #return f'{folder.name}'
    if folder is None or not folder.splited:
        abort(404)
    if folder.owner != current_user:
        abort(403)
    return render_template('subfiles.html', files=folder.subfiles, link_form=link_form) 

@files.route('/files/view/<int:id>')
@login_required
def view_files(id):
    link_form = LinkForm()
    file = Folder.query.get(id)
    if not file:
        abort(404)
    if file.owner != current_user:
        abort(403)
    if 'video' in file.content_type:
        return render_template('video.html', link_form=link_form,id=file.id)
    elif 'pdf' in file.content_type:
        return render_template('pdfviewer.html', link_form=link_form,id=file.id)
    else:
        abort(404)

@files.route('/files/video/<int:id>')
@login_required
def view_video(id):
    file = Folder.query.get(id)
    if not file:
        abort(404)
    if file.owner != current_user:
        abort(403)
    if 'video' in file.content_type:
        print('\n entered\n')
        location = os.path.join(script_location, file.file_location)
        return send_file(location)

@files.route('/files/pdf/<int:id>')
@login_required
def view_pdf(id):
    file = Folder.query.get(id)
    if not file:
        abort(404)
    if file.owner != current_user:
        abort(403)
    if 'pdf' in file.content_type:
        location = os.path.join(script_location, file.file_location)
        return send_file(location)

def clean_up(locations):
    for location in locations:

Zipper/project/main/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import current_user
from project.users.forms import LoginForm, RegisterForm

main = Blueprint('main',__name__)

@main.route('/')
def home():
    if current_user.is_authenticated:
        return redirect(url_for('files.file'))
    login_form = LoginForm()
    signup_form = RegisterForm()
    error = False
    return render_template('index.html', login_form=login_form,
            signup_form=signup_form, error=error)

Zipper/project/templates/401.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="400.css">
  </head>
  <body>
    <div class="container">
      <h2>Oops! Unauthorized</h2>
      <h1>401</h1>
      <p>session not found.</p>
      {% if current_user.is_authenticated %}
      <a href="{{url_for('files.file')}}">Go back home</a>
      {% else %}
      <a href="{{url_for('main.home')}}">Go back home</a>
      {% endif %}
    </div>
  </body>
</html>

Zipper/project/templates/account.html
{% extends 'file_base.html' %}
{% block css %}
<link rel='stylesheet' type='text/css' media='screen'href="{{url_for('static',filename='account.css')}}"> 
{% endblock %}
{% block content %}
 <div class="allcontent my-4 text-align-center ">
    <div class="col-xl-8 order-xl-1">
      <form method="POST" enctype="multipart/form-data">
        {{update_form.hidden_tag()}}
      <div class="card bg-secondarys shadow">
        <div class="card-header border-0">
          <div class="rows align-items-center">
            <div class="cols-8">
              <div class="profile-pic-div"> 
                <img src="{{url_for('static',filename='profile_pics/'+current_user.profile_pic)}}" id="photo">
                {{update_form.profile_pic}}
                <label for="file" id="uploadBtn">Change</label>
              </div>
            </div>
          </div>
        </div>
        <div class="card-body px-5">
            <br>
            {% if update_form.profile_pic.errors %}
                {% for error in update_form.profile_pic.errors %}
                    <span class="text-danger">{{ error }}</span></br>
                {% endfor %}
            {% endif %}
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                  <div class="alert alert-{{ category }}" data-dismiss="alert">
                    <center>{{ message }}</center>
                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
            <h6 class="heading-small text-muted mb-4">User information</h6>
            <div class="pls-lg-4">
              <div class="rows">
                <div class="cols-lg-6">
                  <div class="form-group focused">
                    <label class="form-control-label" for="input-username">Username</label>
                    {% if update_form.username.errors %}
                      {{ update_form.username}}
                        <div class="invalid-feedback d-block">
                            {% for error in update_form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                      {{ update_form.username }}
                    {% endif %}
                  </div>
                </div>
                <div class="cols-lg-6">
                  <div class="form-group">
                    <label class="form-control-label" for="input-email">Email address</label>
                    {% if update_form.email.errors %}
                      {{ update_form.email}}
                        <div class="invalid-feedback d-block">
                            {% for error in update_form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                      {{ update_form.email}}
                    {% endif %}
                  </div>
                </div>
              </div>
              <div class="rows">
                <div class="cols-lg-6">
                  <div class="form-group focused">
                    <label class="form-control-label" for="input-first-name">Current Password</label>
                    {% if update_form.current_password.errors %}
                      {{ update_form.current_password}}
                        <div class="invalid-feedback d-block">
                            {% for error in update_form.current_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                      {{ update_form.current_password}}
                    {% endif %}
                  </div>
                  <div class="form-group focused">
                    <label class="form-control-label" for="input-first-name">New Password</label>
                    {% if update_form.password.errors %}
                      {{ update_form.password}}
                        <div class="invalid-feedback d-block">
                            {% for error in update_form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                      {{ update_form.password}}
                    {% endif %}
                  </div>
                  <div class="form-group focused">
                    <label class="form-control-label" for="input-first-name">Confirm Password</label>
                    {% if update_form.confirm_password.errors %}
                      {{ update_form.confirm_password}}
                        <div class="invalid-feedback d-block">
                            {% for error in update_form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                      {{ update_form.confirm_password}}
                    {% endif %}
                  </div>

                  {{update_form.submit}}
                </div>

              </div>
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
  <script>
    const imgDiv = document.querySelector('.profile-pic-div');
    const img = document.querySelector('#photo');
    const file = document.querySelector('#file');
    const uploadBtn = document.querySelector('#uploadBtn');


    imgDiv.addEventListener('mouseenter', function () {
      uploadBtn.style.display = "block";
    });


    imgDiv.addEventListener('mouseleave', function () {
      uploadBtn.style.display = "none";
    });



    file.addEventListener('change', function () {
      const choosedFile = this.files[0];

      if (choosedFile) {

        const reader = new FileReader();

        reader.addEventListener('load', function () {
          img.setAttribute('src', reader.result);
        });

        reader.readAsDataURL(choosedFile);


      }
    });
  </script>
{% endblock %}

Zipper/project/templates/advanced.html
{% extends 'file_base.html' %}
{% block content %}
<br><br>
<div class="formMain d-flex justify-center align-items-center">
        <div class="formSection my-5 text-center container bg-body rounded shadow  p-4" style="max-width: 600px;">
            <h4 class="display-4">Advanced Option</h4>
            <div class="formContainer text-start mt-4">
                <form method="POST">
                	{{advanced_form.hidden_tag()}}
                    <div class="mb-4">
                        <label for="url" class="form-label">URL</label>
                        {{advanced_form.link}}
                    </div>
                    <div class="mb-4">
                        <label for="url" class="form-label">Compression Level</label>
                        {{advanced_form.level}}
                        </select>
                    </div>
                    <div class="mb-4">
                        <label for="url" class="form-label">Split Volume</label>
                            {{advanced_form.split}}
                        </select> </div>
                    <div class="mb-4">
                        <label for="url" class="form-label">Archive Format</label>
                            {{advanced_form.format}}
                        </select>
                    </div>
                    <button class="btn " style="background: #a349a4;color: aliceblue;"  type='submit'>Submit</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

Zipper/project/templates/files.html
{% extends 'file_base.html' %}
{% block css %}
  <link rel="stylesheet" href="{{url_for('static',filename='style.css')}}">
{% endblock%}
{% block content %}
 <main><br>
        <div class="mainTableContainer">
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                  <div class="alert alert-{{ category }}" data-dismiss="alert">
                    <center>{{ message }}</center>
                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
            <div class="tableHeader">
                <div class="leftCol">
                    <input type="text" class="form-control" placeholder="Search Your Files">
                    <button class="btn btn-secondary">Search</button>
                </div>
                <div class="rightCol">
                    <a href="{{url_for('files.advanced')}}">
                    <button class="btn btn-secondary"><i class="fas fa-sliders-h"></i>  Advanced</button>
                    </a>
                </div>
            </div>
            <div class="tableContainer">

                <div class="tableHead">
                    <div class="tableName">Name</div>
                    <div class="tableSize"><center>Size</center></div>
                    <div class="tableDate">Date Modified</div>
                    <div class="tableMobMore">Option</div>
                </div>
            </div>
            {% for file in files %}
            {% if file.progress != "Finished" %}
            <div class="tableBody ">
                <div class="tableRow progressClass">
                    <div class="tableBodyName">

                        {% if file.progress == 'Virus' %}
                            <div class="progress" style="height: 30px;">
                                <div class="progress-bar progress-bar-striped bg-danger progress-bar-animated" role="progressbar"
                                    style="width: 100%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
                                    <b>Virus Detected</b>
                                </div>
                            </div>
                        {% elif file.progress == 'Failed' %}
                        <div class="progress" style="height: 30px;">
                                <div class="progress-bar progress-bar-striped bg-danger progress-bar-animated" role="progressbar"
                                    style="width: 100%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
                                    <b>Failed</b>
                                </div>
                            </div>
                        {% else %}
                            <div class="progress" style="height: 30px;">
                                <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar"
                                    style="width: 100%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
                                    <b>{{ file.progress }}</b>
                                </div>
                            </div>
                        {% endif %}

                        <div class="nameIcon">
                            <span class="{{file.content_type}}Icon"></span>
                            <span id="tableBodyName"> {{file.name}}</span>
                        </div>
                    </div>
                    <div class="tableBodySize">
                        {% if file.size > 1024 %}
                            {% if file.size > 1024*1024 %}
                                {{ (file.size/1024*1024)|int }} GB
                            {% else %}
                                {{ (file.size/1024)|int }} MB
                            {% endif %}
                        {% else %}
                            {{ (file.size)|int }} KB
                        {% endif %}
                    </div>
                    <div class="tableBodyDate">

                        {{ file.date.strftime('%Y-%m-%d') }}
                    </div>
                    <!-- <div class="tableBodyMobDots">
                        <div class="dropdown">
                            <button class="dropdown-toggle" type="button" id="dropdownMenuButton1"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fas fa-download"></i>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                <li><a class="dropdown-item" href="#"><i class="fas fa-file-download"></i>
                                        Download</a></li>
                                <li><a class="dropdown-item" href="#"><i class="fas fa-link"></i> Copy Link</a></li>
                                <li><a class="dropdown-item" href="#"><i class="fas fa-cloud-upload-alt"></i> Move
                                        to Drive</a></li>
                            </ul>
                        </div>
                    </div> -->
                </div>
            </div>
            {% else %}
            <div class="tableBody">
                <div class="tableRow">
                    <div class="tableBodyName">
                        <!-- <div class="progress">
                                <div class="progress-bar progress-bar-striped bg-success" role="progressbar"
                                    style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
                                </div>
                            </div> -->
                        {% if file.splited %}

                        <div class="nameIcon" onclick="location.href='/files/subfiles/{{file.id}}'">
                            <span class="{{file.content_type}}Icon"></span>
                            <span id="tableBodyName"> {{file.name}} </span>
                        </div>
                        {% else %}
                        <div class="nameIcon">
                            <span class="{{file.content_type}}Icon"></span>
                            <span id="tableBodyName"> {{file.name}} </span>
                        </div>
                        {% endif %}
                    </div>
                    <div class="tableBodySize">
                        {% if file.size > 1024 %}
                            {% if file.size > 1024*1024 %}
                                {{ (file.size/1024*1024)|int }} GB
                            {% else %}
                                {{ (file.size/1024)|int }} MB
                            {% endif %}
                        {% else %}
                            {{ (file.size)|int }} KB
                        {% endif %}
                    </div>
                    <div class="tableBodyDate">
                        {{ file.date.strftime('%Y-%m-%d') }}
                    </div>
                    <div class="tableBodyMobDots">
                        <div class="dropdown">
                            <button class="dropdown-toggle" type="button" id="dropdownMenuButton1"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fas fa-download"></i>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                {% if file.splited %}
                                <li><a class="dropdown-item" href="/files/subfiles/{{file.id}}"><i class="fas fa-folder-open"></i>  Open</a></li>

                                {% if "pdf" in file.content_type or "video" in file.content_type %}
                                <li><a class="dropdown-item" href="/files/view/{{file.id}}"><i class="fas fa-eye"></i> View</a></li>
                                {% endif %}

                                {% else %}
                                <li><a class="dropdown-item" href="/download/{{file.id}}"><i class="fas fa-file-download"></i>
                                        Download</a></li>

                                {% if "pdf" in file.content_type or "video" in file.content_type %}
                                <li><a class="dropdown-item" href="/files/view/{{file.id}}"><i class="fas fa-eye"></i> View</a></li>
                                {% endif %}

                                <li><a class="dropdown-item" href="/get_link/{{file.id}}"><i class="fas fa-link"></i> Copy Link</a></li>
				<li><a class="dropdown-item" href="/files/delete/{{file.id}}"><i class="fas fa-trash-alt"></i> Delete</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
        </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>

{% endblock %}

Zipper/project/templates/pdfviewer.html
{% extends 'file_base.html' %}

{% block content %}
<style>
center{
  height: 500px;
}
.textLayer{
  height: 500px;
}
iframe{
  height: 650px;
}

</style>
    <main class='textLayer'>
    <br>
    <br>
    <br>
    <center>
      <h1>PDF Viewer</h1>
    <iframe src="/files/pdf/{{id}}" width="90%">
    </iframe>
    </center>
    </main>
{% endblock %}

Zipper/project/templates/video.html
{% extends 'file_base.html' %}
{% block css %}
  <link rel="stylesheet" href="{{url_for('static',filename='videoplayer.css')}}">
{% endblock%}
{% block content %}
 <main id='main'>
 	<br><br>
<div class="mainTableContainer">
	<center>
		<u><h1>Video Player</h1></u>
   <div class="player">
	   <video class="player__video viewer" src="{{url_for('files.view_video',id=id)}}"></video>

     <div class="player__controls">
       <div class="progress">
        <div class="progress__filled"></div>
       </div>
       <button class="player__button toggle" title="Toggle Play">►</button>
       <input type="range" name="volume" class="player__slider" min="0" max="1" step="0.05" value="1">
       <input type="range" name="playbackRate" class="player__slider" min="0.5" max="2" step="0.1" value="1">
       <button data-skip="-10" class="player__button">« 10s</button>
       <button data-skip="25" class="player__button">25s »</button>
     </div>
   </div>
   </center>
</div>
 <script src="{{url_for('static',filename='videoplayer.js')}}"></script>
</main>
{% endblock %}